# -*- coding: utf-8 -*-
"""LAB5task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qL3tPkSeLACG7IdBumegZakprFqwlaCE
"""

import numpy as np
import pandas as pd

data=pd.read_csv("Concrete_Data.xls.csv")

data.head()

data.isnull().any()

# #features: Cement (component 1)(kg in a m^3 mixture)
#                 Blast Furnace Slag (component 2)(kg in a m^3 mixture)
#                 Fly Ash (component 3)(kg in a m^3 mixture)
#                 Water  (component 4)(kg in a m^3 mixture)
#                 Superplasticizer (component 5)(kg in a m^3 mixture)
#                 Coarse Aggregate  (component 6)(kg in a m^3 mixture)
#                 Fine Aggregate (component 7)(kg in a m^3 mixture)
#                 Age (day)
#  # Target : Concrete compressive strength(MPa, megapascals) ''')

x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,train_size=.80,random_state=2021)

"""**1-MSE**"""

from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor(criterion='mse',random_state=2021,splitter='best')
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

print('accuracy score=',model.score(x_train, y_train))



from sklearn import tree
import graphviz
dot_tree = tree.export_graphviz(model,filled=True,rounded=True)
graph = graphviz.Source(dot_tree, format="png") 
graph

"""**2-MAE**"""

from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor(criterion='mae',random_state=2021,splitter='best')
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

print('accuracy score=',model.score(x_train, y_train))

from sklearn import tree
import graphviz
dot_tree = tree.export_graphviz(model ,filled=True,rounded=True)
graph = graphviz.Source(dot_tree, format="png") 
graph

from sklearn.metrics import confusion_matrix,classification_report
matrix=confusion_matrix(y_test,y_pred)

